import { ROLES } from "./roles";

export const PERMISSIONS = {
  DASHBOARD_READ: "dashboard.read",
  DASHBOARD_SHIFT_REPORT_EXPORT: "dashboard.shiftReport.export",

  CONFIRMATION_READ: "confirmation.read",
  CONFIRMATION_WRITE: "confirmation.write",

  MATERIAL_READ: "material.read",
  MATERIAL_GOODS_ISSUE: "material.goodsIssue",
  MATERIAL_GOODS_RECEIPT: "material.goodsReceipt",

  OEE_READ: "oee.read",
  OEE_DOWNTIME_WRITE: "oee.downtime.write",
  OEE_EXPORT: "oee.export",

  QUALITY_INSPECTION_READ: "quality.inspection.read",
  QUALITY_INSPECTION_WRITE: "quality.inspection.write",
  NC_HANDLING_READ: "quality.nc.read",
  NC_HANDLING_WRITE: "quality.nc.write",

  PRODUCTION_ORDERS_READ: "productionOrders.read",
  PRODUCTION_ORDERS_WRITE: "productionOrders.write",

  WORK_CENTERS_READ: "workCenters.read",
  WORK_CENTERS_WRITE: "workCenters.write",

  SAP_INTEGRATION_READ: "sapIntegration.read",
  SAP_INTEGRATION_CONFIG: "sapIntegration.config",
  USER_MANAGEMENT: "users.manage",
};

const operationalReadWritePermissions = [
  PERMISSIONS.DASHBOARD_READ,
  PERMISSIONS.DASHBOARD_SHIFT_REPORT_EXPORT,
  PERMISSIONS.CONFIRMATION_READ,
  PERMISSIONS.CONFIRMATION_WRITE,
  PERMISSIONS.MATERIAL_READ,
  PERMISSIONS.MATERIAL_GOODS_ISSUE,
  PERMISSIONS.MATERIAL_GOODS_RECEIPT,
  PERMISSIONS.OEE_READ,
  PERMISSIONS.OEE_DOWNTIME_WRITE,
  PERMISSIONS.OEE_EXPORT,
  PERMISSIONS.QUALITY_INSPECTION_READ,
  PERMISSIONS.QUALITY_INSPECTION_WRITE,
  PERMISSIONS.NC_HANDLING_READ,
  PERMISSIONS.NC_HANDLING_WRITE,
  PERMISSIONS.PRODUCTION_ORDERS_READ,
  PERMISSIONS.PRODUCTION_ORDERS_WRITE,
  PERMISSIONS.WORK_CENTERS_READ,
  PERMISSIONS.WORK_CENTERS_WRITE,
  PERMISSIONS.SAP_INTEGRATION_READ,
];

export const ROLE_PERMISSIONS = {
  [ROLES.OPERATOR]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.CONFIRMATION_READ,
    PERMISSIONS.CONFIRMATION_WRITE,
    PERMISSIONS.MATERIAL_READ,
    PERMISSIONS.MATERIAL_GOODS_ISSUE,
    PERMISSIONS.OEE_READ,
    PERMISSIONS.OEE_DOWNTIME_WRITE,
  ],
  [ROLES.SUPERVISOR]: operationalReadWritePermissions,
  [ROLES.QUALITY]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.QUALITY_INSPECTION_READ,
    PERMISSIONS.QUALITY_INSPECTION_WRITE,
    PERMISSIONS.NC_HANDLING_READ,
    PERMISSIONS.NC_HANDLING_WRITE,
  ],
  [ROLES.PLANNER]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.PRODUCTION_ORDERS_READ,
    PERMISSIONS.PRODUCTION_ORDERS_WRITE,
    PERMISSIONS.WORK_CENTERS_READ,
    PERMISSIONS.WORK_CENTERS_WRITE,
    PERMISSIONS.CONFIRMATION_READ,
  ],
  [ROLES.ADMIN]: [
    ...operationalReadWritePermissions,
    PERMISSIONS.SAP_INTEGRATION_READ,
    PERMISSIONS.SAP_INTEGRATION_CONFIG,
    PERMISSIONS.USER_MANAGEMENT,
  ],
};
